### ISSUE TITLE
MVP Code Refactoring, Cleanup & Docs Checklist 

### ISSUE THREAD

**Issue by nomadtechie** [bocoup/test262-automation#50]
Amal
- [ ] remove `_` and replace with symbols
- [ ] add jsdoc docs 
- [ ] review error handling
- [x] cleanup index.js
- [x] move diff list &  filtering out of git utl & into its own class
- [ ] clean up outcome manager & exporter relationship
- [ ] integrete #45 into the resolver algorithm
- [x] investigate using `common-tags`templale helper for notes used in export
- [ ]  lint project
- [ ] return if no diffs were found in source

Bmac
- [x] get first sha's for repo
- [x] extend cli with choices
- [ ] test script with forked test-262 & real webkit once
- [ ] document chron job & pr flow
- [ ] setup 2 instances of chron job & document
- [ ] extend Reporter with new modified & remaned outcomes (pending Amal's merge)
